#!/bin/ksh 

set -xa

export RUN_ENVIR=${RUN_ENVIR:-nco}

if [ $RUN_ENVIR != nco ] ; then
  PBEG=${PBEG:-""}
  $PBEG
  . ${PARA_CONFIG:-/global/save/${LOGNAME}/para_gfs/pr4devb/para_config}
  export userid=$LOGNAME
fi

export PS4='$SECONDS + '
date

# #### 02/02/2016 #############################
# SETUP GFS FCST PROCESSING VARIABLES
# #############################################

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=${pid:-$$}


####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gfs}
export RUN=${RUN:-gfs}


####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# RERUN    - Rerun fcst from beginning (default yes)
# VERBOSE  - Specify Verbose Output in exglobal_fcst_nems.sh.ecf
####################################
export RERUN=${RERUN:-YES}
export VERBOSE=${VERBOSE:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEgfs=${HOMEgfs:-$NWROOT/gfs.${gfs_ver}}
export HOMEglobal=${HOMEglobal:-$NWROOT/global_shared.${global_shared_ver}}
export EXECgsm=${EXECgsm:-$HOMEglobal/exec}
export SCRgsm=${SCRgsm:-$HOMEglobal/scripts}
export USHgsm=${USHgsm:-$HOMEglobal/ush}
export PARMgsm=${PARMgsm:-$HOMEglobal/parm}

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg

##############################################
# Define GES directories
##############################################
gespath=${gespath:-$GESROOT/${envir}}

##############################################
# WCOSS_C environment settings
##############################################
export machine=${machine:-WCOSS_C}
export MKL_NUM_THREADS=1
export MKL_CBWR=AVX
export MP_MPILIB=mpich2
export USEBULKXFER=NO
export MPICH_GNI_COLL_OPT_OFF=MPI_Alltoallv
export IOBUF_PARAMS=${IOBUF_PARAMS:-'*:size=8M:verbose'}
export APRUN=${APRUN:-"aprun -j1 -n $ntasks -N $ptile -d $threads -cc depth"}
export APRUNC=${APRUNC:-"aprun -n 1 -N 1 -j 1 -d 24 -cc depth"}


####################################
# Specify Special Fcst Vars
####################################
. $GFS_PARM 
#
msg="HAS BEGUN on `hostname`"

#
#
  export GFSOUT=$DATA/$RUN.$cycle.grdr.chgres
  export SFNOUT=$DATA/$RUN.$cycle.sfcr.chgres
  export NSNOUT=$DATA/$RUN.$cycle.nstr.chgres

  if [ $IDVC = 1 ] ; then
     export SIGLEVEL=$FIXgsm/global_siglevel.l$LEVS.txt
  elif [ $IDVC = 2 ] ; then
     export SIGLEVEL=$FIXgsm/global_hyblev.l$LEVS.txt
  fi

# Run global_chgres
  export CHGRESVARS="use_ufo=$use_ufo,nst_anl=$NST_ANL,rdgrid=$rdgrid,idvc=$IDVC,idvt=$idvt,idsl=$IDSL,IDVM=$idvm,OUTTYP=$OUTTYP_CH,nopdpvv=$nopdpvv"
  export OMP_NUM_THREADS_CH=${OMP_NUM_THREADS_CH:-24}
  $GLOBAL_CHGRES
  rc=$?
  if [[ $rc -ne 0 ]];then $PERR;exit 1;fi
  cat $pgmout

  export GRDI=$GFSOUT
  export SFCI=$SFNOUT
  export NSTI=$NSNOUT

  if [ -f $GRDI -a -f $SFCI -a -f $NSTI ] ; then
     msg="Forecast Starting with Fields Produced by CHGRES"
     postmsg "$jlogfile" "$msg"
  else
     msg="FATAL ERROR fields Produced by CHGRES Not Available for $job"
     postmsg "$jlogfile" "$msg"
     export pgm=$job
     export err=911
     $ERRSCRIPT
  fi

aprun -q -n 1 /home/SSPMRES/rphani/TCO_Data_Preparation/nemsio_replace_topo $SIGINP $GFSOUT ${JCAP}
#-----------------------------------

date
